[profile.default]
src = "contracts"
test = "test"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [{ access = "read", path = "./data" }]

[rpc_endpoints]
xlayer = "https://rpc.xlayer.tech"
