"""Build the Vectra mark, wordmark and lockups from the app's own values.

Run:  python3 build.py        (see README.md for the font step first)

Everything here is read off web/app/page.tsx. If the app's Mark() or Header()
changes, change it there and re-run this — never edit the SVGs by hand.
"""
import math, pathlib
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

# ── FROM web/app/page.tsx ───────────────────────────────────────────────────
#   Mark():   viewBox 0 0 22 22
#             circle cx=11 cy=11 r=10 stroke=--bone stroke-width=1 fill=none
#             circle cx=11.8 cy=10.4 r=5.4 fill=--cyan
#   Header(): gap 12; span fontSize 17 fontWeight 600 letterSpacing -0.01em
#
# Shipped offset = hypot(0.8, 0.6) = 1.0 = 10% of the radius at 36.87deg.
# DESIGN.md §7 says "approximately eight percent"; see README.
BOX, CX, CY, R, SW = 22.0, 11.0, 11.0, 10.0, 1.0
DX, DY, DR = 11.8, 10.4, 5.4
GAP, FS, LS = 12.0, 17.0, -0.01
GROUND, BONE, CYAN = "#0e1620", "#e8e4da", "#00d4c4"

# opsz pinned at the app's 17px. The opsz=96 shapes are ~9% narrower and are a
# different wordmark; a logo must be one fixed shape at every size.
FONT = '/tmp/bricolage-17-600.ttf'

f = TTFont(FONT)
gs, upem, cmap, hmtx = f.getGlyphSet(), f['head'].unitsPerEm, f.getBestCmap(), f['hmtx']
cap = f['OS/2'].sCapHeight
kern = f['kern'].kernTables[0].kernTable if 'kern' in f else {}


def word(text, px):
    """Outlined text, baseline at y=0. Outlines rather than <text>: a wordmark
    that needs a webfont renders as Helvetica in Figma, in email, offline."""
    s, x, parts, prev = px / upem, 0.0, [], None
    for ch in text:
        g = cmap[ord(ch)]
        if prev is not None:
            x += kern.get((prev, g), 0) + LS * upem
        pen = SVGPathPen(gs)
        gs[g].draw(TransformPen(pen, Transform(s, 0, 0, -s, x * s, 0)))
        if pen.getCommands():
            parts.append(pen.getCommands())
        x += hmtx[g][0]
        prev = g
    return " ".join(parts), x * s


ring = lambda c: (f'<circle cx="{CX:g}" cy="{CY:g}" r="{R:g}" fill="none" '
                  f'stroke="{c}" stroke-width="{SW:g}"/>')
disc = lambda c: f'<circle cx="{DX:g}" cy="{DY:g}" r="{DR:g}" fill="{c}"/>'

NOTE = ("<!-- Vectra. Generated by brand/build.py from web/app/page.tsx;\n"
        "     wordmark is Bricolage Grotesque opsz=17 wght=600 at -0.01em,\n"
        "     outlined. viewBox units ARE the app's units. Never hand-edit. -->\n")


def svg(name, w, h, body, px):
    pathlib.Path(name).write_text(
        NOTE + f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:g} {h:g}" '
        f'width="{px:g}" height="{px * h / w:.4g}" role="img" aria-label="Vectra">\n'
        f'{body}</svg>\n')
    print(f"   {name:32s} {w:7.3f} x {h:g}")


svg("vectra-icon.svg", BOX, BOX, f'  {ring(BONE)}\n  {disc(CYAN)}\n', 256)
svg("vectra-icon-on-light.svg", BOX, BOX, f'  {ring(GROUND)}\n  {disc(CYAN)}\n', 256)
svg("vectra-icon-mono.svg", BOX, BOX,
    f'  {ring("currentColor")}\n  {disc("currentColor")}\n', 256)

# Favicon: stroke thickened because 1/22 of a 16px tab icon is under half a
# pixel and disappears. The offset is preserved exactly.
svg("vectra-favicon.svg", BOX, BOX,
    f'  <rect width="{BOX:g}" height="{BOX:g}" fill="{GROUND}"/>\n'
    f'  <circle cx="{CX:g}" cy="{CY:g}" r="{R - 0.3:g}" fill="none" '
    f'stroke="{BONE}" stroke-width="1.7"/>\n  {disc(CYAN)}\n', 64)

d, adv = word("Vectra", FS)
base, x0 = CY + cap / upem * FS / 2, BOX + GAP
for nm, rc, dc, tc in (("vectra-lockup.svg", BONE, CYAN, BONE),
                       ("vectra-lockup-on-light.svg", GROUND, CYAN, GROUND),
                       ("vectra-lockup-mono.svg", "currentColor", "currentColor", "currentColor")):
    svg(nm, x0 + adv, BOX, f'  {ring(rc)}\n  {disc(dc)}\n'
        f'  <path transform="translate({x0:g},{base:.4f})" d="{d}" fill="{tc}"/>\n', 640)

dw, advw = word("Vectra", 100.0)
asc = cap / upem * 100
for nm, c in (("vectra-wordmark.svg", BONE), ("vectra-wordmark-mono.svg", "currentColor")):
    svg(nm, advw, 100.0,
        f'  <path transform="translate(0,{(100 + asc) / 2:.3f})" d="{dw}" fill="{c}"/>\n', 600)

ds, advs = word("Vectra", 9.0)
W, H = max(BOX, advs), BOX + 5 + cap / upem * 9
svg("vectra-lockup-stacked.svg", W, H,
    f'  <g transform="translate({(W - BOX) / 2:.3f},0)">{ring(BONE)}{disc(CYAN)}</g>\n'
    f'  <path transform="translate({(W - advs) / 2:.3f},{H:.3f})" d="{ds}" fill="{BONE}"/>\n', 320)

off = math.hypot(DX - CX, DY - CY)
print(f"\n   offset {off:.3f} = {off / R * 100:.1f}% of R at "
      f"{math.degrees(math.atan2(CY - DY, DX - CX)):.2f}deg")
print(f"   wordmark advance {adv:.3f}  baseline {base:.3f}  text x {x0:g}")
